version: "3.8"

services:
  db:
    image: postgres:15
    container_name: vitalcare_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vitaluser
      POSTGRES_PASSWORD: vitalpass
      POSTGRES_DB: vitalcare
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
